name: Demo
on:
  pull_request:
    types:
      - opened
      - closed
  workflow_dispatch:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello"      