name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: true
        # default: target-files
        type: string
jobs:
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.jar-file }}"  
      - name: Deploy
        run: echo "Deploying..."